# BindingManager Configuration

telegram-token: "YOUR_TELEGRAM_BOT_TOKEN" # Replace with your actual Telegram bot token
language: "en" # Available languages: en, uk
code-length-bytes: 3 # Length of generated codes in bytes (e.g., 3 bytes = 6 hex characters)
binding-code-timeout-seconds: 300 # Timeout for binding/unbinding codes in seconds (default: 300 seconds = 5 minutes)
2fa-timeout-seconds: 120 # Timeout for 2FA login requests in seconds (default: 120 seconds = 2 minutes)

# 2FA Mode:
# - "after_password": (Default) Trigger 2FA only after a successful password login via XAuth.
# - "always": Trigger 2FA on every player join, regardless of previous authentication steps (e.g., even after auto-login).
two-factor-mode: "after_password"

# A list of Telegram user IDs that will have administrative privileges in the bot.
# To get your ID, send a message to the @userinfobot bot.
admins:
  - 123456789 # Replace with your Telegram user ID
  - 987654321 # Replace with another Telegram user ID

database:
  # Available providers: sqlite, mysql
  provider: "sqlite"
  sqlite:
    file: "bindings.sqlite"
    bindings-table: "bindings"
    codes-table: "temporary_codes"
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
    database: "binding_manager"
    bindings-table: "bindings"
    codes-table: "temporary_codes"

network:
  # Allows forcing a domain name to resolve to a specific IP address.
  # Use only in case of DNS resolution problems.
  # Example: example.com: 192.168.1.1
  force-resolve-hosts:
    # example.com: 192.168.1.1
    # api.myplugin.com: 203.0.113.42

  # Path to a custom CA certificate bundle for cURL.
  # Use if standard system certificates do not work.
  custom-ca-bundle: "" # Example: "plugins/MyPlugin/cacert.pem"
